name: Update README

on:
  schedule:
    - cron: '12 * * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@master
        with:
          ## File to render
          filename: github-metrics.svg
          ## Auth
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          ## Plugins
          # Used Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          # Music
          plugin_music: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/6RBUOx0knUzK0K9hfjNwrt
