name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: malouro/github-activity-readme@master
        env:
          EMOJI_MERGE_PR: '🎊'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}